# Generated by Django 3.2.6 on 2021-08-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('correct_answers', models.IntegerField(default=0)),
                ('game_in_process', models.BooleanField(default=False)),
                ('current_game_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100)),
                ('game_in_process', models.BooleanField(default=False)),
                ('game_id', models.IntegerField(blank=True)),
                ('users', models.ManyToManyField(to='tg_bot.User')),
            ],
        ),
    ]
