# Generated by Django 3.2.6 on 2021-08-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_game_id',
            field=models.IntegerField(default=-1),
        ),
    ]
